on: [pull_request]
name: Test PR
jobs:
  test:
    name: test pr
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: test
      uses: franmomu/github-actions-test@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
